### ISSUE TITLE
momo插件

### ISSUE THREAD

**Issue by hemengyao0909** [mmmlllnnn/com.mln.momoxposed#1]
你好，请问你这个插件我可以用作背单词使用吗？请问如何使用这个插件

**Comment by kiven12600** [comment]
大佬用的是啥封装的APP哇，我封装以后一直获取hock，然后软件进步去

**Comment by mmmlllnnn** [comment]
> 大佬用的是啥封装的APP哇，我封装以后一直获取hock，然后软件进步去

封装？你的意思是你要自己从源码打包么？还是说只是想用这个插件？

**Comment by kiven12600** [comment]
是想用插件，我刚开始是内置进墨墨背单词的软件里面去，但是用不了，这个不咋会操作

**Comment by mmmlllnnn** [comment]
> 是想用插件，我刚开始是内置进墨墨背单词的软件里面去，但是用不了，这个不咋会操作

原app有加固，修改包后会触发人家的签名校验，所以像lspatch、太极等免root的框架不太能用呐。得lsposed才行。

**Comment by kiven12600** [comment]
噢噢，明白了，我去试试
