### ISSUE TITLE
弹出已找到 hook 函数的消息后要多长时间啊

### ISSUE THREAD

**Issue by DongDong20050214** [mmmlllnnn/com.mln.momoxposed#11]
弹出已找到 hook 函数的消息后要多长时间啊，等很长时间没反应，手机是Redmi k50 pro

**Comment by mmmlllnnn** [comment]
> 弹出已找到 hook 函数的消息后要多长时间啊，等很长时间没反应，手机是Redmi k50 pro

弹出消息提示后关掉后台重新进就生效了

**Comment by DongDong20050214** [comment]
我看之前的问题有lsposed模块，是需要在手机里安装lsposed模块吗
