### ISSUE TITLE
一直显示"正在寻找hook函数"

### ISSUE THREAD

**Issue by Kurokara** [mmmlllnnn/com.mln.momoxposed#12]
没有弹出已找到hook函数，运行环境:k50u A13 lsposed 1.9.3_mod(7244) API100 arm64-v8a

**Comment by mmmlllnnn** [comment]
> 没有弹出已找到hook函数，运行环境:k50u A13 lsposed 1.9.3_mod(7244) API100 arm64-v8a

请问墨墨的版本是？还有我需要你app里面，"我的"界面的截图，不知道能否提供一下。

**Comment by Kurokara** [comment]
> > 没有弹出已找到hook函数，运行环境:k50u A13 lsposed 1.9.3_mod(7244) API100 arm64-v8a
> 
> 请问墨墨的版本是？还有我需要你app里面，"我的"界面的截图，不知道能否提供一下。

解决了，之前用的是最新版不知道为什么不行，换了5.3.75就可以了

**Comment by 6386288** [comment]
我遇到这个问题了，呜呜呜
