### ISSUE TITLE
请教如何寻找类名、方法名

### ISSUE THREAD

**Issue by OwnerCM** [mmmlllnnn/com.mln.momoxposed#3]
可能是因为版本原因，我使用你方法中的类名、方法名在SimpleHook中配置无法找到该方法。能否请教一下如何获取com.maimemo.android.momo.d0这个类名及方法名？
 Class<?> aClass = XposedHelpers.findClass("com.maimemo.android.momo.d0", classLoader);
                        XposedBridge.hookAllMethods(aClass, "V", new XC_MethodHook() {
                            @Override
                            protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                                XposedBridge.log("已找到hook的类");
                                param.setResult(99966); // 将返回值修改为 99966
                                XposedBridge.log("hook成功，修改单词上限为99966");

                            }

**Comment by mmmlllnnn** [comment]
₍^◐   ̫  ◐^₎ Dump出dex后，根据这个版本的代码块搜相似？？？加固搞的类名和方法名每版本都不一样艾

**Comment by OwnerCM** [comment]
> ₍^◐   ̫ ◐^₎ Dump出dex后，根据这个版本的代码块搜相似？？？加固搞的类名和方法名每版本都不一样艾

我看到网上很多说墨墨有服务端检测，如果超过服务端的单词量会封号，大佬有碰到这种情况么？

**Comment by mmmlllnnn** [comment]
对，有检测哎，上传自己单词数据有几率封的

**Comment by CrazyNutLz** [comment]
> ₍^◐   ̫ ◐^₎ Dump出dex后，根据这个版本的代码块搜相似？？？加固搞的类名和方法名每版本都不一样艾

大佬你是用的什么方法dump ，我用firdadump最新版本的dex后部分dex打不开，需要修复吗？

**Comment by CrazyNutLz** [comment]
谢谢大佬的代码 ，v5.3.45_775 ，class: com.maimemo.android.momo.F0   method:d0

**Comment by OwnerCM** [comment]
> 谢谢大佬的代码 ，v5.3.45_775 ，class: com.maimemo.android.momo.f0 method:d0 @OwnerCM @mmmlllnnn

相同版本，我在simplehook中使用这个类名和方法名竟然没有成功

**Comment by mmmlllnnn** [comment]
> > 谢谢大佬的代码 ，v5.3.45_775 ，class: com.maimemo.android.momo.f0 method:d0 @OwnerCM @mmmlllnnn
> 
> 相同版本，我在simplehook中使用这个类名和方法名竟然没有成功

感觉可能是hook时机太早了，dex还没解出来

**Comment by mmmlllnnn** [comment]
> 谢谢大佬的代码 ，v5.3.45_775 ，class: com.maimemo.android.momo.f0   method:d0
> @OwnerCM @mmmlllnnn 

可以判断下，搞搞多版本适配的，或者有什么代码特征之类

**Comment by CrazyNutLz** [comment]
> > 谢谢大佬的代码 ，v5.3.45_775 ，class: com.maimemo.android.momo.f0 method:d0 @OwnerCM @mmmlllnnn
> 
> 相同版本，我在simplehook中使用这个类名和方法名竟然没有成功

{"className":"com.maimemo.android.momo.f0","methodName":"d0","resultValues":"9999","hookPoint":"after"}

**Comment by OwnerCM** [comment]
> {"className":"com.maimemo.android.momo.f0","methodName":"d0","resultValues":"9999","hookPoint":"after"}

这个可以，加了参数类型反倒是不行，谢谢大佬！

**Comment by CrazyNutLz** [comment]
> > {"className":"com.maimemo.android.momo.f0","methodName":"d0","resultValues":"9999","hookPoint":"after"}
> 
> 这个可以，加了参数类型反倒是不行，谢谢大佬！

那个方法本来就没参数。。
