### ISSUE TITLE
5.3.70失效

### ISSUE THREAD

**Issue by Librafu0930** [mmmlllnnn/com.mln.momoxposed#7]
5.3.70小米14失效 登录界面闪退

**Comment by mmmlllnnn** [comment]
> 5.3.70小米14失效 登录界面闪退

先登录进去，再开模块试试呢_(:з」∠)_，我也用的5.3.70，刚退了一下，没有发现登录问题。

**Comment by Librafu0930** [comment]
在正在寻找hook函数那边一直闪退 是我操作有问题吗

**Comment by Librafu0930** [comment]
![Uploading Screenshot_2024-09-21-22-54-26-065_com.maimemo.android.momo.jpg…]()

**Comment by mmmlllnnn** [comment]
是不是你的每日复习量，或者其他什么数据超过了600个，然后被误识别hook了。如果不是的话，需要你换个账号，看能否复现，来排除是账号问题还是bug(´⊙ω⊙`)

**Comment by Librafu0930** [comment]
我用的是lspatch 内嵌的 现在登录都登陆不进去呀

**Comment by Librafu0930** [comment]
![Screenshot_2024-09-21-23-10-48-995_com maimemo android momo](https://github.com/user-attachments/assets/4b81be1b-5a11-409c-81f1-d26dabc06524)

**Comment by Librafu0930** [comment]
![Uploading Screenshot_2024-09-21-22-54-26-065_com.maimemo.android.momo.jpg…]()

**Comment by mmmlllnnn** [comment]
> 我用的是lspatch 内嵌的 现在登录都登陆不进去呀

阿这........

有加固的app不太能用lspatch的，这种免root框架应该是修改的classloader来注入，它只能修改classloader不变的app，但实际这个app的classloader是解密后动态载入的。(⋟﹏⋞)

看来闪退和模块没关系了。

你要是还想用的话，就只能mt管理器直接修改墨墨背单词的apk包了，我看了一下5.3.70的函数是：com.maimemo.android.momo.f0.d0
把这个返回值改大就可以了。

**Comment by serendipity091** [comment]
大佬，为什么我一打开墨墨背单词就闪退，oppo系统。
