### ISSUE TITLE
闪退问题

### ISSUE THREAD

**Issue by serendipity091** [mmmlllnnn/com.mln.momoxposed#8]
用opatch插入模块后安装，一打开墨墨背单词就闪退，oppo系统，可能是没适配，希望大佬适配一下，十分感谢

**Comment by serendipity091** [comment]
是内嵌模块，是不是需要mt管理器修改，怎么修改啊，最后的签名校检我会。

**Comment by mmmlllnnn** [comment]
> 是内嵌模块，是不是需要mt管理器修改，怎么修改啊，最后的签名校检我会。

1. 得先把dex脱出来，然后修改这个函数的返回值（单词数量）：com.maimemo.android.momo.f0.d0

2. 修复dex并把它打包到apk中

3. 修改app启动的入口到新的dex

4. 过签名校验

挺复杂的，我并没有试过
